---

apiVersion: v1
kind: Pod
metadata:
  name: random-2
  namespace: step-1
  labels:
    demo/project: com.gft.techoffice.techsnacks-20211104
    demo/app: step-1
    demo/module: random-2
    active: "yes"
spec:
  containers:
    - name: server
      image: com.gft.techoffice.techsnacks-20211104.server:no-daemon
      imagePullPolicy: Never
      env:
        - name: TOPIC
          value: topic-a
        - name: MODULE
          value: server-2
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  hostIPC: true
