---

apiVersion: v1
kind: Namespace
metadata:
  name: step-1a
  labels: 
    demo/project: com.gft.techoffice.techsnacks-20211104
    demo/app: step-1
    config.istio.io/admission-webhooks: disabled
    istio-injection: disabled

---

apiVersion: v1
kind: Pod
metadata:
  name: random-3
  namespace: step-1a
  labels:
    demo/project: com.gft.techoffice.techsnacks-20211104
    demo/app: step-1
    demo/module: random-3
    active: "yes"
spec:
  containers:
    - name: server
      image: com.gft.techoffice.techsnacks-20211104.server:no-daemon
      imagePullPolicy: Never
      env:
        - name: TOPIC
          value: topic-a
        - name: MODULE
          value: server-3
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  hostIPC: true
