FROM debian:buster-slim AS BUILDIMAGE

ARG GITHASH
ARG TIMESTAMP
ARG COMPONENT

RUN apt-get update && \
    apt-get install -y libbsd-dev && \
    apt-get install -y git gcc make binutils build-essential && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir /tmp/build

COPY c /tmp/build/src


WORKDIR /tmp/build/src/server
RUN COMPONENT=server GITHASH=${GITHASH} TIMESTAMP=${TIMESTAMP} make clean
RUN COMPONENT=server GITHASH=${GITHASH} TIMESTAMP=${TIMESTAMP} make dep lib
RUN COMPONENT=server GITHASH=${GITHASH} TIMESTAMP=${TIMESTAMP} make all

WORKDIR /tmp/build/src/client
RUN COMPONENT=client GITHASH=${GITHASH} TIMESTAMP=${TIMESTAMP} make clean
RUN COMPONENT=client GITHASH=${GITHASH} TIMESTAMP=${TIMESTAMP} make dep lib
RUN COMPONENT=client GITHASH=${GITHASH} TIMESTAMP=${TIMESTAMP} make all

# ----------------------------------------------------------------------------

FROM debian:buster-slim

ARG GITHASH
ARG TIMESTAMP
ARG COMPONENT

RUN apt-get update && \
    apt-get install -y libbsd0 && \
    apt-get install -y psmisc procps lsof strace ltrace gdb && \
    rm -rf /var/lib/apt/lists/*
COPY --from=BUILDIMAGE "/tmp/build/src/dist/bin/server" "/opt/server"
COPY --from=BUILDIMAGE "/tmp/build/src/dist/bin/client" "/opt/client"
